# Generated by Django 4.0.5 on 2024-01-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0159_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Daman and Diu', 'Daman and Diu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chattisgarh', 'Chattisgarh'), ('Gujrat', 'Gujrat'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'packed'), ('On The Wey', 'On The Way'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('C', 'Vitamin C'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('C', 'Vitamin C'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('C', 'Vitamin C'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('C', 'Vitamin C'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('E', 'Vitamin E'), ('K', 'Vitamin K'), ('D3', 'Vitamin D3'), ('HS', 'Herbal, Specialty Supplements'), ('GH', 'General Health'), ('PC', 'Personal Care'), ('AN', 'Antioxidants'), ('WH', 'Women health'), ('A', 'Vitamin A'), ('DH', 'Digestive Health'), ('AV', 'Ayurvedic'), ('C', 'Vitamin C'), ('OG', 'Organic'), ('SH', 'Sexual health'), ('VM', 'Vitamins&Minerals'), ('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('IH', 'Immune Health')], max_length=3),
        ),
    ]
