# Generated by Django 4.0.6 on 2024-01-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0157_rename_delivery_zipcode_orderplaced_delivery_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Daman and Diu', 'Daman and Diu'), ('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('On The Wey', 'On The Way'), ('Delivered', 'Delivered'), ('Packed', 'packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='popular',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='category',
            field=models.CharField(choices=[('MH', 'Men Health'), ('B12', 'Vitamin B12'), ('OG', 'Organic'), ('WH', 'Women health'), ('AV', 'Ayurvedic'), ('IH', 'Immune Health'), ('D3', 'Vitamin D3'), ('PC', 'Personal Care'), ('A', 'Vitamin A'), ('C', 'Vitamin C'), ('AN', 'Antioxidants'), ('HS', 'Herbal, Specialty Supplements'), ('DH', 'Digestive Health'), ('E', 'Vitamin E'), ('SH', 'Sexual health'), ('K', 'Vitamin K'), ('GH', 'General Health'), ('VM', 'Vitamins&Minerals')], max_length=3),
        ),
    ]
